config/routes.rb
Vectest::Application.routes.draw do
  resources :records
  root 'records#index'

end

app/models/record.rb
class Record
  
  @@cutoff = 0.15
  
  #@@lime ||= ENV["MAGIC"].split(",").map {|x| x.to_f }
  #require 'matrix'
  #extend Matrix
  
  #@@limelight = [1, 0, 1, 0, 1]
  include Mongoid::Document
  #include Matrix
  #extend Matrix
  field :xid, type: String
  field :content, type: Array
  
 # def self.dotprod(array1, array2)
 #   sum = 0
 #   len = (array1.length) - 1
  #  for i in 0..len
  #    sum += (array1[i] * array2[i])
 #   end
 #   return sum
 # end
  
  #def self.dot(array)
  #  sum = 0
  #  for i in 0..4
  #    sum += (array[i] * @@lime[i])
  #  end
   # sum
  #end
  
 # def apnumber
   
    #Record.dotprod(content, [1, 1, 0, 1, 1])
    #Record.dotprod(content, ENV["MAGIC"])
  #  Record.dotprod(content, @@lime)
   
  #end
  
  #def square
    #dotprod(content, content)
    #end
  
  def apnumber
    #Record.dot(content)
    Cruncher.crunch(content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  # GET /records
  # GET /records.json
  def index
    @records = Record.all
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render action: 'show', status: :created, location: @record }
      else
        format.html { render action: 'new' }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:xid, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def dotprod(array1, array2)
    sum = 0
    len = (array1.length) - 1
    for i in 0..len
      sum += (array1[i] * array2[i])
    end
    return sum
      
    
  end
end

app/helpers/records_helper.rb
module RecordsHelper
  def dotprod(array1, array2)
    sum = 0
    len = (array1.length) - 1
    for i in 0..len
      sum += (array1[i] * array2[i])
    end
    return sum
      
    
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vectest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/records/_form.html.erb
<%= form_for(@record) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :xid %><br>
    <%= f.text_field :xid %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing record</h1>

<%= render 'form' %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<h1 class = "higher">Higher Order</h1>

<table>
  <thead>
    <tr>
      <th>Xid</th>
      <th>Content</th>
      <th>AP Number</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.xid %></td>
        <td><%= record.content %></td>
		<td><%= record.apnumber %></td>
        <td><%= link_to 'Show', record %></td>
        <td><%= link_to 'Edit', edit_record_path(record) %></td>
        <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Record', new_record_path %>

app/views/records/new.html.erb
<h1>New record</h1>

<%= render 'form' %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Xid:</strong>
  <%= @record.xid %>
</p>

<p>
  <strong>Content:</strong>
  <%= @record.content %>
</p>

<p>
  <strong>AP Number:</strong>
  <%= @record.apnumber %>
</p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>